name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Terraform version
        id: tfenv
        run: |
          echo "version=$(<terraform-version)" >> $GITHUB_OUTPUT
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ steps.tfenv.outputs.version }}
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: terraform init

      - name: Check for Terraform plan changes
        id: check_changes
        run: echo ::set-output name=changed::$(terraform show -json tfplan | jq '.resource_changes | length > 0')

      - name: Terraform apply
        if: steps.check_changes.outputs.changed == 'true'
        run: terraform apply -auto-approve tfplan

      - name: Send notification on failure
        if: failure()
        run: |
          echo "Terraform deployment failed. Check the workflow logs for details."
      
      - name: Send notification on success
        if: success()
        run: |
          echo "Terraform deployment successful."